#!/usr/bin/perl -w

#----------------------------------------------------------------------
# copyright (C) 2002 Mitel Networks Corporation
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
# 		
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 		
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307  USA
# 
# Technical support for this program is available from Mitel Networks 
# Please visit our web site www.mitel.com/sme/ for details.
#----------------------------------------------------------------------
use strict;

=head1 NAME

validate-lexicon - Check the provided files for syntactical correctness.

=head1 SYNOPSIS

    validate-lexicon file [file...]

=head1 DESCRIPTION

Parses the given lexicon files to check for syntactical correctness.
Files can be either straight lexicons, or lexicons in the __DATA__
section of a Perl script. Returns non-zero exit status if one or more 
lexicons fails.

=head1 AUTHOR

Mitel Networks Corporation

=cut

use XML::Parser;

my $status = 0;

foreach my $filename ( @ARGV )
{
    my $contents;

    open(XML, $filename) || die "Couldn't open $filename\n";

    while ( <XML> )
    {
	$contents .= $_;
        $contents = '' if ( /^__DATA__/ );
    }

    my $p = new XML::Parser (Style => 'Tree', 
			     ProtocolEncoding => 'ISO-8859-1' );

    my $xml;
	
    my $result = eval { $xml = $p->parse( $contents ); };

    undef $p;

    if ($result)
    {
        warn "XML parse of $filename succeeded\n";
    }
    else
    {
        warn "XML parse of $filename FAILED\n$@\n";
        $status = 1;
    }
}

exit $status;
